trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'staticWebAppResourceGroup'
  storageAccountName: 'stwebappdevuks01'
  location: 'uk south'
  cdnProfileName: 'cdnWebApp'
  cdnEndpointName: 'cdnWebApp'

steps:
- checkout: self

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'webapp-service-connection'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/rg-deploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/rg-deploy.parameters.json'
 


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'webapp-service-connection'
    subscriptionId: '2572aea5-6815-4f8e-861e-8b36ad01f50f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy.parameters.json'
    deploymentMode: 'Incremental'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'webapp-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch -d '$web' -s $(Build.SourcesDirectory)/webapp --account-name $(storageAccountName)
  displayName: 'Upload Static Website'