trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'staticWebAppResourceGroup'
  storageAccountName: 'stwebappdevuks01'
  location: 'uk south'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'static-webapp-service-connection'
    subscriptionId: '2572aea5-6815-4f8e-861e-8b36ad01f50f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deploy.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deploy.parameters.json'
    deploymentMode: 'Incremental'

- task: CopyFiles@2
  displayName: 'Copy deployment content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/website-static'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/website-static
    cleanTargetFolder: true
