trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'staticWebAppResourceGroup'
  storageAccountName: 'stwebappdevuks01'
  location: 'uk south'

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'static-webapp-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch -d '$web' -s $(Build.SourcesDirectory)/webapp --account-name $(storageAccountName)
  displayName: 'Upload Static Website'